// These thises 2
//
// Add to Person a createGreetingsForFriends method which will return an array of strings - each string in the array is a greeting generated by the createGreeting method. For example:
//
// > var alfie = new Person('Alfie');
// > var anushka = new Person('Anushka');
// > var henrique = new Person('Henrique');
// > alfie.addFriend(anushka);
// > alfie.addFriend(henrique);
// > alfie.createGreetingsForFriends();
// ["Yo Anushka! from Alfie.", "Yo Henrique! from Alfie."]
// Do this without using a loop but by using map instead.

function Person(name) {
  this.name = name;
  this.friends = [];
}

Person.prototype.addFriend = function(friend) {
  this.friends.push(friend);
};

Person.prototype.createGreeting = function(other) {
  return 'Yo ' + other.name + '! from ' + this.name + '.';
};

Person.prototype.greet = function(other) {
  console.log(this.createGreeting(other));
};

Person.prototype.createGreetingsForFriends = function () {
  var that = this;
  var greetings = this.friends.map(function(friend) {
    that.greet(friend);
  });
  return greetings;
};

var alfie = new Person('Alfie');
var anushka = new Person('Anushka');
var henrique = new Person('Henrique');
alfie.addFriend(anushka);
alfie.addFriend(henrique);
alfie.createGreetingsForFriends();
